/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageAccountDTO } from './storageAccountDTO';
import { ApplianceJobOutput } from './applianceJobOutput';
import { SubscriptionDTO } from './subscriptionDTO';


export interface ApplianceSessionContext { 
    id?: string;
    tenantId?: string | null;
    selectedSubscriptionId?: string | null;
    selectedSubscription?: SubscriptionDTO;
    selectedStorageAccountId?: string | null;
    selectedStorageAccounts?: Array<StorageAccountDTO> | null;
    userOid?: string | null;
    availableSubscriptions?: Array<SubscriptionDTO> | null;
    availableStorageAccounts?: Array<StorageAccountDTO> | null;
    jobOutput?: Array<ApplianceJobOutput> | null;
    currentJobOutput?: ApplianceJobOutput;
}

