/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RetentionPolicyTupleContainer } from './retentionPolicyTupleContainer';
import { TableStorageTableRetentionPolicy } from './tableStorageTableRetentionPolicy';
import { TableStorageTableRetentionPolicyEnforcementResult } from './tableStorageTableRetentionPolicyEnforcementResult';
import { TableStorageEntityRetentionPolicyEnforcementResult } from './tableStorageEntityRetentionPolicyEnforcementResult';
import { TableStorageEntityRetentionPolicy } from './tableStorageEntityRetentionPolicy';


export interface ApplianceJobOutput { 
    id?: string;
    tableRetentionResult?: TableStorageTableRetentionPolicyEnforcementResult;
    tableEntityRetentionResult?: TableStorageEntityRetentionPolicyEnforcementResult;
    tableEntityRetentionPolicy?: TableStorageEntityRetentionPolicy;
    tableRetentionPolicy?: TableStorageTableRetentionPolicy;
    readonly retentionPolicyTuples?: Array<RetentionPolicyTupleContainer> | null;
    retentionPolicyJobs?: Array<RetentionPolicyTupleContainer> | null;
}

