/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowOperation } from './workflowOperation';


export interface AvailableCommand { 
    availableCommandId?: string | null;
    userOid?: string | null;
    tenantId?: string | null;
    subscriptionId?: string | null;
    subscriptionName?: string | null;
    workflowOperation?: WorkflowOperation;
    commandParameterJson?: string | null;
    worklowOperationDisplayMessage?: string | null;
    menuLabel?: string | null;
}

