/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DiagnosticsRetentionSurfaceItemDescriptor = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const DiagnosticsRetentionSurfaceItemDescriptor = {
    NUMBER_0: 0 as DiagnosticsRetentionSurfaceItemDescriptor,
    NUMBER_1: 1 as DiagnosticsRetentionSurfaceItemDescriptor,
    NUMBER_2: 2 as DiagnosticsRetentionSurfaceItemDescriptor,
    NUMBER_3: 3 as DiagnosticsRetentionSurfaceItemDescriptor,
    NUMBER_4: 4 as DiagnosticsRetentionSurfaceItemDescriptor,
    NUMBER_5: 5 as DiagnosticsRetentionSurfaceItemDescriptor,
    NUMBER_6: 6 as DiagnosticsRetentionSurfaceItemDescriptor,
    NUMBER_7: 7 as DiagnosticsRetentionSurfaceItemDescriptor,
    NUMBER_8: 8 as DiagnosticsRetentionSurfaceItemDescriptor
};

