/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RetentionSurfaceItemDescriptor } from './retentionSurfaceItemDescriptor';
import { DiagnosticsRetentionSurfaceItemDescriptor } from './diagnosticsRetentionSurfaceItemDescriptor';


export interface DiagnosticsRetentionSurfaceItemEntity { 
    itemDescription?: string | null;
    itemExists?: boolean;
    itemWillBeDeleted?: boolean;
    id?: string;
    storageAccountId?: string | null;
    suscriptionId?: string | null;
    tableName?: string | null;
    documentationLink?: string | null;
    itemDescriptor?: DiagnosticsRetentionSurfaceItemDescriptor;
    itemType?: RetentionSurfaceItemDescriptor;
}

