/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DurableOrchestrationStateDTO } from './durableOrchestrationStateDTO';
import { AvailableCommand } from './availableCommand';
import { ApplianceSessionContext } from './applianceSessionContext';
import { SubscriptionDTO } from './subscriptionDTO';


export interface OperatorPageModel { 
    applianceAPIEndPoint?: string | null;
    easyAuthAccessToken?: string | null;
    queryWorkflowCheckpointStatusEndpoint?: string | null;
    allScopes?: Array<string> | null;
    subscriptions?: Array<SubscriptionDTO> | null;
    applianceUrl?: Array<string> | null;
    orchestrations?: Array<DurableOrchestrationStateDTO> | null;
    availableCommands?: Array<AvailableCommand> | null;
    accessToken?: string | null;
    isMustRenderApplianceConfig?: boolean;
    applianceSessionContext?: ApplianceSessionContext;
    resetDeviceUrl?: string | null;
}

