/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OrchestrationRuntimeStatus = 0 | 1 | 2 | 3 | 4 | 5 | 6 | -1;

export const OrchestrationRuntimeStatus = {
    NUMBER_0: 0 as OrchestrationRuntimeStatus,
    NUMBER_1: 1 as OrchestrationRuntimeStatus,
    NUMBER_2: 2 as OrchestrationRuntimeStatus,
    NUMBER_3: 3 as OrchestrationRuntimeStatus,
    NUMBER_4: 4 as OrchestrationRuntimeStatus,
    NUMBER_5: 5 as OrchestrationRuntimeStatus,
    NUMBER_6: 6 as OrchestrationRuntimeStatus,
    NUMBER_MINUS_1: -1 as OrchestrationRuntimeStatus
};

