/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TableStorageTableRetentionPolicyEnforcementResult } from './tableStorageTableRetentionPolicyEnforcementResult';
import { StorageAccountDTO } from './storageAccountDTO';
import { TableStorageRetentionPolicy } from './tableStorageRetentionPolicy';
import { TableStorageEntityRetentionPolicyEnforcementResult } from './tableStorageEntityRetentionPolicyEnforcementResult';


export interface RetentionPolicyTupleContainer { 
    id?: string;
    tableStorageRetentionPolicy?: TableStorageRetentionPolicy;
    storageAccount?: StorageAccountDTO;
    tableStoragePolicyEnforcementResult?: TableStorageTableRetentionPolicyEnforcementResult;
    tableStorageEntityPolicyEnforcementResult?: TableStorageEntityRetentionPolicyEnforcementResult;
}

