/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RetentionSurfaceItemDescriptor = 0 | 1;

export const RetentionSurfaceItemDescriptor = {
    NUMBER_0: 0 as RetentionSurfaceItemDescriptor,
    NUMBER_1: 1 as RetentionSurfaceItemDescriptor
};

