/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StorageAccountDTO { 
    requestingAzureAdUserOid?: string | null;
    isSelected: boolean;
    storageAccountKind?: string | null;
    id?: string | null;
    location?: string | null;
    name?: string | null;
    storageAccountType?: string | null;
    skuName?: string | null;
    tenantId?: string | null;
    subscriptionId?: string | null;
}

