/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionPoliciesDTO } from './subscriptionPoliciesDTO';


export interface SubscriptionDTO { 
    isSelected?: boolean;
    requestingAzureAdUserOid?: string | null;
    id?: string | null;
    authorizationSource?: string | null;
    managedByTenants?: Array<string> | null;
    subscriptionId?: string | null;
    tenantId?: string | null;
    displayName?: string | null;
    state?: string | null;
    subscriptionPolicies?: SubscriptionPoliciesDTO;
}

