/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetricRetentionSurfaceEntity } from './metricRetentionSurfaceEntity';
import { PolicyEnforcementMode } from './policyEnforcementMode';


export interface TableStorageTableRetentionPolicy { 
    id?: string;
    metricRetentionSurface?: MetricRetentionSurfaceEntity;
    policyEnforcementMode?: PolicyEnforcementMode;
    deleteOlderTablesThanCurrentMonthMinusThis?: number;
    oldestRetainedTable?: string;
    mostRecentRetainedTable?: string;
    tableNames?: Array<string> | null;
}

