/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiagnosticsRetentionSurfaceEntity } from './diagnosticsRetentionSurfaceEntity';
import { PolicyEnforcementMode } from './policyEnforcementMode';


export interface TableStorageEntityRetentionPolicy { 
    id?: string;
    diagnosticsRetentionSurface?: DiagnosticsRetentionSurfaceEntity;
    policyEnforcementMode?: PolicyEnforcementMode;
    numberOfDays?: number;
    oldestRetainedEntity?: string;
    mostRecentRetainedEntity?: string;
    tableNames?: Array<string> | null;
}

