/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WorkflowOperation = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const WorkflowOperation = {
    NUMBER_0: 0 as WorkflowOperation,
    NUMBER_1: 1 as WorkflowOperation,
    NUMBER_2: 2 as WorkflowOperation,
    NUMBER_3: 3 as WorkflowOperation,
    NUMBER_4: 4 as WorkflowOperation,
    NUMBER_5: 5 as WorkflowOperation,
    NUMBER_6: 6 as WorkflowOperation,
    NUMBER_7: 7 as WorkflowOperation
};

