/**
 * Storage Account Cleaner For Azure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { ApplianceSessionContext } from '../model/models';
import { OperatorPageModel } from '../model/models';
import { TableStorageEntityRetentionPolicy } from '../model/models';
import { TableStorageRetentionPolicy } from '../model/models';
import { TableStorageTableRetentionPolicy } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class RetentionEntitiesService {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getApplianceSessionContext(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ApplianceSessionContext>;
    public getApplianceSessionContext(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<ApplianceSessionContext>>;
    public getApplianceSessionContext(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<ApplianceSessionContext>>;
    public getApplianceSessionContext(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling getApplianceSessionContext.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling getApplianceSessionContext.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.get<ApplianceSessionContext>(`${this.configuration.basePath}/api/RetentionEntities/GetApplianceSessionContext/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param xTableRetentionCurrentStorageAccount 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEntityRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<TableStorageEntityRetentionPolicy>;
    public getEntityRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<TableStorageEntityRetentionPolicy>>;
    public getEntityRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<TableStorageEntityRetentionPolicy>>;
    public getEntityRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling getEntityRetentionPolicyForStorageAccount.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling getEntityRetentionPolicyForStorageAccount.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }
        if (xTableRetentionCurrentStorageAccount !== undefined && xTableRetentionCurrentStorageAccount !== null) {
            headers = headers.set('x-table-retention-current-storage-account', String(xTableRetentionCurrentStorageAccount));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.get<TableStorageEntityRetentionPolicy>(`${this.configuration.basePath}/api/RetentionEntities/GetEntityRetentionPolicyForStorageAccount/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param xTableRetentionCurrentStorageAccount 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<TableStorageRetentionPolicy>;
    public getRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<TableStorageRetentionPolicy>>;
    public getRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<TableStorageRetentionPolicy>>;
    public getRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling getRetentionPolicyForStorageAccount.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling getRetentionPolicyForStorageAccount.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }
        if (xTableRetentionCurrentStorageAccount !== undefined && xTableRetentionCurrentStorageAccount !== null) {
            headers = headers.set('x-table-retention-current-storage-account', String(xTableRetentionCurrentStorageAccount));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.get<TableStorageRetentionPolicy>(`${this.configuration.basePath}/api/RetentionEntities/GetRetentionPolicyForStorageAccount/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param xTableRetentionCurrentStorageAccount 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTableRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<TableStorageTableRetentionPolicy>;
    public getTableRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<TableStorageTableRetentionPolicy>>;
    public getTableRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<TableStorageTableRetentionPolicy>>;
    public getTableRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling getTableRetentionPolicyForStorageAccount.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling getTableRetentionPolicyForStorageAccount.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }
        if (xTableRetentionCurrentStorageAccount !== undefined && xTableRetentionCurrentStorageAccount !== null) {
            headers = headers.set('x-table-retention-current-storage-account', String(xTableRetentionCurrentStorageAccount));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.get<TableStorageTableRetentionPolicy>(`${this.configuration.basePath}/api/RetentionEntities/GetTableRetentionPolicyForStorageAccount/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param applianceSessionContext 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setApplianceSessionContext(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, applianceSessionContext?: ApplianceSessionContext, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<ApplianceSessionContext>;
    public setApplianceSessionContext(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, applianceSessionContext?: ApplianceSessionContext, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<ApplianceSessionContext>>;
    public setApplianceSessionContext(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, applianceSessionContext?: ApplianceSessionContext, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<ApplianceSessionContext>>;
    public setApplianceSessionContext(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, applianceSessionContext?: ApplianceSessionContext, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling setApplianceSessionContext.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling setApplianceSessionContext.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.post<ApplianceSessionContext>(`${this.configuration.basePath}/api/RetentionEntities/SetApplianceSessionContext/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            applianceSessionContext,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param xTableRetentionCurrentStorageAccount 
     * @param tableStorageEntityRetentionPolicy 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setEntityRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageEntityRetentionPolicy?: TableStorageEntityRetentionPolicy, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<TableStorageEntityRetentionPolicy>;
    public setEntityRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageEntityRetentionPolicy?: TableStorageEntityRetentionPolicy, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<TableStorageEntityRetentionPolicy>>;
    public setEntityRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageEntityRetentionPolicy?: TableStorageEntityRetentionPolicy, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<TableStorageEntityRetentionPolicy>>;
    public setEntityRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageEntityRetentionPolicy?: TableStorageEntityRetentionPolicy, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling setEntityRetentionPolicyForStorageAccount.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling setEntityRetentionPolicyForStorageAccount.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }
        if (xTableRetentionCurrentStorageAccount !== undefined && xTableRetentionCurrentStorageAccount !== null) {
            headers = headers.set('x-table-retention-current-storage-account', String(xTableRetentionCurrentStorageAccount));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.post<TableStorageEntityRetentionPolicy>(`${this.configuration.basePath}/api/RetentionEntities/SetEntityRetentionPolicyForStorageAccount/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            tableStorageEntityRetentionPolicy,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param xTableRetentionCurrentStorageAccount 
     * @param operatorPageModel 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setOperatorPageModel(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, operatorPageModel?: OperatorPageModel, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<OperatorPageModel>;
    public setOperatorPageModel(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, operatorPageModel?: OperatorPageModel, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<OperatorPageModel>>;
    public setOperatorPageModel(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, operatorPageModel?: OperatorPageModel, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<OperatorPageModel>>;
    public setOperatorPageModel(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, operatorPageModel?: OperatorPageModel, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling setOperatorPageModel.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling setOperatorPageModel.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }
        if (xTableRetentionCurrentStorageAccount !== undefined && xTableRetentionCurrentStorageAccount !== null) {
            headers = headers.set('x-table-retention-current-storage-account', String(xTableRetentionCurrentStorageAccount));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.post<OperatorPageModel>(`${this.configuration.basePath}/api/RetentionEntities/SetOperatorPageModel/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            operatorPageModel,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param xTableRetentionCurrentStorageAccount 
     * @param tableStorageRetentionPolicy 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageRetentionPolicy?: TableStorageRetentionPolicy, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<TableStorageRetentionPolicy>;
    public setRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageRetentionPolicy?: TableStorageRetentionPolicy, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<TableStorageRetentionPolicy>>;
    public setRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageRetentionPolicy?: TableStorageRetentionPolicy, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<TableStorageRetentionPolicy>>;
    public setRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageRetentionPolicy?: TableStorageRetentionPolicy, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling setRetentionPolicyForStorageAccount.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling setRetentionPolicyForStorageAccount.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }
        if (xTableRetentionCurrentStorageAccount !== undefined && xTableRetentionCurrentStorageAccount !== null) {
            headers = headers.set('x-table-retention-current-storage-account', String(xTableRetentionCurrentStorageAccount));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.post<TableStorageRetentionPolicy>(`${this.configuration.basePath}/api/RetentionEntities/SetRetentionPolicyForStorageAccount/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            tableStorageRetentionPolicy,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param tenantId 
     * @param oid 
     * @param xTableRetentionCurrentSubscription 
     * @param xTableRetentionCurrentStorageAccount 
     * @param tableStorageTableRetentionPolicy 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setTableRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageTableRetentionPolicy?: TableStorageTableRetentionPolicy, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<TableStorageTableRetentionPolicy>;
    public setTableRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageTableRetentionPolicy?: TableStorageTableRetentionPolicy, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<TableStorageTableRetentionPolicy>>;
    public setTableRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageTableRetentionPolicy?: TableStorageTableRetentionPolicy, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<TableStorageTableRetentionPolicy>>;
    public setTableRetentionPolicyForStorageAccount(tenantId: string, oid: string, xTableRetentionCurrentSubscription?: string, xTableRetentionCurrentStorageAccount?: string, tableStorageTableRetentionPolicy?: TableStorageTableRetentionPolicy, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling setTableRetentionPolicyForStorageAccount.');
        }
        if (oid === null || oid === undefined) {
            throw new Error('Required parameter oid was null or undefined when calling setTableRetentionPolicyForStorageAccount.');
        }

        let headers = this.defaultHeaders;
        if (xTableRetentionCurrentSubscription !== undefined && xTableRetentionCurrentSubscription !== null) {
            headers = headers.set('x-table-retention-current-subscription', String(xTableRetentionCurrentSubscription));
        }
        if (xTableRetentionCurrentStorageAccount !== undefined && xTableRetentionCurrentStorageAccount !== null) {
            headers = headers.set('x-table-retention-current-storage-account', String(xTableRetentionCurrentStorageAccount));
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType_ = 'text';
        }

        return this.httpClient.post<TableStorageTableRetentionPolicy>(`${this.configuration.basePath}/api/RetentionEntities/SetTableRetentionPolicyForStorageAccount/${encodeURIComponent(String(tenantId))}/${encodeURIComponent(String(oid))}`,
            tableStorageTableRetentionPolicy,
            {
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
